drop table if EXISTS marlo_project_submission;
create table `marlo_project_submission` (
  `CRP` varchar(50) not null,
  `project id` varchar(21) not null default '',
  `Project link` varchar(168) not null default '',
  `Project Title` longtext,
  `Flagships` varchar(50) default null,
  `Regions` varchar(50) default null,
  `Status` varchar(9) default null,
  `Management Liaison` longtext,
  `Management Liaison acronym` varchar(255) default null,
  `Management Liaison Contact Person` text,
  `Lead Institution` longtext,
  `Project Leader` text,
  `Submission_status` varchar(13)  not null default '',
  `submitted_by` varchar(255),
  `Submission Date` varchar(34) default null,
  `Submission Justification` longtext,
  `Unsubmission Justification` longtext,
  `section_id` bigint(20) default '0',
  `section_name` varchar(255) default null comment 'Some section name (would be the action name)',
  `Section status` varchar(10) default '',
  `indicator_ID` varchar(22) default null,
  `indicator_ID_2` varchar(22) default null,
  `missing fields` text,
  `is_evaluated` varchar(3) not null default '',
  `updated_date` datetime not null default '0000-00-00 00:00:00',
  `Phase` longtext not null,
  `phase_name` text not null,
  `phase_year` int(11) not null
) engine=innodb default charset=utf8;
