-- Job entry log table

CREATE TABLE marlobi.pentaho_job_log
(
  ID_BATCH INT
, CHANNEL_ID VARCHAR(255)
, LOG_DATE DATETIME
, TRANSNAME VARCHAR(255)
, STEPNAME VARCHAR(255)
, LINES_READ BIGINT
, LINES_WRITTEN BIGINT
, LINES_UPDATED BIGINT
, LINES_INPUT BIGINT
, LINES_OUTPUT BIGINT
, LINES_REJECTED BIGINT
, ERRORS BIGINT
, RESULT VARCHAR(5)
, NR_RESULT_ROWS BIGINT
, NR_RESULT_FILES BIGINT
)
;
CREATE INDEX IDX_pentaho_job_log_1 ON marlobi.pentaho_job_log(ID_BATCH)
;
