\. D:\Github\MARLO-BI\Tables\01dim\CR_br_fs_group_locations.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_ccm.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_fs_group_institutions.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_deliverables.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_flagships.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_geo_scopes.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_institutions.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_locations.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_milestones.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_oicrs.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_owners.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_proj.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_sdg.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_smo_org_types.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_srf_cci.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_br_group_srf_targets.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_coss_cutting_markers.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_crps.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_deliverables_info.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_ext_partners.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_flagships.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_fs_agreement_statuses.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_fs_info.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_fs_intersect_group_institutions.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_fs_intersect_group_locations.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_funding_windows.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_geo_scopes.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_innovations_info.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_innovation_stg.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_innovation_types.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_ccm.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_deliverables.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_flagships.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_geo_scopes.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_institutions.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_locations.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_milestones.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_oicrs.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_owners.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_proj.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_sdg.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_smo_org_types.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_srf_cci.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_intersect_group_srf_targets.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_locations.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_milestones_info.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_oicrs_info.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_policies_info.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_policies_owners.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_policy_investment_types.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_projects_info.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_sdg.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_smo_org_types.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_srf_cci.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_srf_targets.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_stage_processes.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_stg_maturities.sql
\. D:\Github\MARLO-BI\Tables\01dim\CR_dim_year.sql
\. D:\Github\MARLO-BI\Tables\02stg\deliverables\CR_bi_stg_deliverables_full_data.sql
\. D:\Github\MARLO-BI\Tables\02stg\deliverables\CR_bi_stg_deliverables_included_ar.sql
\. D:\Github\MARLO-BI\Tables\02stg\deliverables\CR_bi_stg_deliverables_metadata.sql
\. D:\Github\MARLO-BI\Tables\02stg\deliverables\CR_stg_deliverables_info.sql
\. D:\Github\MARLO-BI\Tables\02stg\funding_sources\CR_stg_fs_info.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_ccm.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_deliverables.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_flagships.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_geo_scopes.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_institutions.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_locations.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_milestones.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_oicrs.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_owners.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_proj.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_sdg.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_smo_org_types.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_srf_cci.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_br_group_srf_targets.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_crps.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_current_phases.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_ext_partners.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_geo_scopes.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_ccm.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_deliverables.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_flagships.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_geo_scopes.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_institutions.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_locations.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_milestones.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_oicrs.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_owners.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_proj.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_sdg.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_smo_org_types.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_srf_cci.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_intersect_group_srf_targets.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_milestones.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_oircs_info.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_policies_info.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_ccm.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_ccm.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_deliverables.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_flaghips.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_geo_scopes.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_institutions.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_locations.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_milestones.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_oicrs.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_owners.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_proj.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_sdg.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_smo_org_types.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_srf_cci.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_group_srf_targets.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_intersect_group_flagships.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_intersect_group_geo_scopes.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_pre_intersect_group_institutions.sql
\. D:\Github\MARLO-BI\Tables\02stg\gendim\CR_stg_sdg.sql
\. D:\Github\MARLO-BI\Tables\02stg\innovations\CR_stg_innovations_info.sql
\. D:\Github\MARLO-BI\Tables\02stg\projects\CR_stg_projects_info.sql
\. D:\Github\MARLO-BI\Tables\03fact\CR_fact_fs.sql
\. D:\Github\MARLO-BI\Tables\03fact\CR_fact_innovations.sql
\. D:\Github\MARLO-BI\Tables\03fact\CR_fact_oicrs.sql
\. D:\Github\MARLO-BI\Tables\03fact\CR_fact_policies.sql
\. D:\Github\MARLO-BI\Tables\03fact\CR_fact_project_budgets.sql
\. D:\Github\MARLO-BI\Tables\03fact\CR_fact_summary_indicators.sql
\. D:\Github\MARLO-BI\Tables\03fact\CR_pre_fs_fact.sql
\. D:\Github\MARLO-BI\Tables\03fact\CR_pre_innovations_fact.sql
\. D:\Github\MARLO-BI\Tables\03fact\CR_pre_oicrs_fact.sql
\. D:\Github\MARLO-BI\Tables\03fact\CR_pre_policies_fact.sql
\. D:\Github\MARLO-BI\Tables\03fact\CR_pre_project_budgets_fact.sql
\. D:\Github\MARLO-BI\Tables\03fact\CR_pre_summary_indicators_fact.sql
\. D:\Github\MARLO-BI\Tables\04misc\CR_process_log.sql
